version: '3.9'
services:  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - sgil_network

  celery-worker:
    build: .
    command: celery -A celery_worker.celery_config.celery worker --loglevel=info --concurrency=4 -Q email_queue,logging_queue
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_ACCEPT_CONTENT=json
      - CELERY_TASK_SERIALIZER=json
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - ADMIN_EMAIL=
      - LOGGING_SERVICE_URL=http://sgil-monitoreo-service:8090/logs
    healthcheck:
      test: ["CMD-SHELL", "celery -A celery_worker.celery_config.celery inspect ping  || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5  
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - sgil_network
 

  flower:
    build: .
    command: celery -A celery_worker.celery_config.celery flower --broker=redis://redis:6379/0
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
      celery-worker:
        condition: service_healthy
    
    networks:
      - sgil_network

  
networks:
  sgil_network:
    external: true